# Generated by Django 2.2.6 on 2019-10-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkassets',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='officeassets',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='ramassets',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='securityassets',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='serverassets',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='storageassets',
            name='sn',
        ),
        migrations.AlterField(
            model_name='diskassets',
            name='sn',
            field=models.CharField(max_length=128, verbose_name='硬盘SN号'),
        ),
    ]
