# Generated by Django 2.2.6 on 2019-10-15 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherassets',
            name='other_admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_admin', to=settings.AUTH_USER_MODEL, verbose_name='资产管理员'),
        ),
        migrations.AddField(
            model_name='officeassets',
            name='assets',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_assets', to='assets.Assets'),
        ),
        migrations.AddField(
            model_name='nicassets',
            name='assets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic_assets', to='assets.Assets'),
        ),
        migrations.AddField(
            model_name='networkassets',
            name='assets',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets'),
        ),
        migrations.AddField(
            model_name='idcassets',
            name='idc_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ContractAssets', verbose_name='机房合同'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Assets'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='new_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.NewAssetApprovalZone'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='事件执行人'),
        ),
        migrations.AddField(
            model_name='domainassets',
            name='domain_admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_admin', to=settings.AUTH_USER_MODEL, verbose_name='域名管理员'),
        ),
        migrations.AddField(
            model_name='diskassets',
            name='assets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_assets', to='assets.Assets'),
        ),
        migrations.AddField(
            model_name='cpuassets',
            name='assets',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_assets', to='assets.Assets'),
        ),
        migrations.AddField(
            model_name='cloudassets',
            name='cloud_admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cloud_admin', to=settings.AUTH_USER_MODEL, verbose_name='云平台管理员'),
        ),
        migrations.AddField(
            model_name='cabinetassets',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to='assets.IDCAssets'),
        ),
        migrations.AddField(
            model_name='businessassets',
            name='business_charge',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='业务负责人'),
        ),
        migrations.AddField(
            model_name='assets',
            name='assets_admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_admin', to=settings.AUTH_USER_MODEL, verbose_name='资产管理员'),
        ),
        migrations.AddField(
            model_name='assets',
            name='assets_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_approved', to=settings.AUTH_USER_MODEL, verbose_name='批准人'),
        ),
        migrations.AddField(
            model_name='assets',
            name='assets_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.BusinessAssets', verbose_name='所属业务线'),
        ),
        migrations.AddField(
            model_name='assets',
            name='assets_cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_cabinet', to='assets.CabinetAssets', verbose_name='所在机柜'),
        ),
        migrations.AddField(
            model_name='assets',
            name='assets_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ContractAssets', verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='assets',
            name='assets_idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_idc', to='assets.IDCAssets', verbose_name='所在机房'),
        ),
        migrations.AddField(
            model_name='assets',
            name='assets_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ManufacturerAssets', verbose_name='厂商'),
        ),
        migrations.AddField(
            model_name='assets',
            name='assets_tags',
            field=models.ManyToManyField(blank=True, to='assets.TagAssets', verbose_name='资产标签'),
        ),
        migrations.AlterUniqueTogether(
            name='ramassets',
            unique_together={('assets', 'ram_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='nicassets',
            unique_together={('assets', 'nic_model', 'nic_mac')},
        ),
        migrations.AlterUniqueTogether(
            name='diskassets',
            unique_together={('assets', 'disk_sn')},
        ),
    ]
