# Generated by Django 2.2.6 on 2019-10-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20191015_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newassetapprovalzone',
            old_name='ram_size',
            new_name='ram_volume',
        ),
    ]
