# Generated by Django 2.2.6 on 2019-10-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20191017_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverassets',
            name='hostname',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='主机名'),
        ),
    ]
