# Generated by Django 2.2.6 on 2019-10-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20191017_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpuassets',
            old_name='core_count',
            new_name='cpu_core_count',
        ),
        migrations.RenameField(
            model_name='cpuassets',
            old_name='count',
            new_name='cpu_count',
        ),
        migrations.RenameField(
            model_name='cpuassets',
            old_name='model',
            new_name='cpu_model',
        ),
    ]
