# Generated by Django 2.2.6 on 2019-10-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20191016_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudassets',
            options={'verbose_name': '云平台资产表', 'verbose_name_plural': '云平台资产表'},
        ),
        migrations.AlterModelOptions(
            name='domainassets',
            options={'verbose_name': '域名表', 'verbose_name_plural': '域名表'},
        ),
        migrations.AlterModelTable(
            name='cloudassets',
            table='imu_cloud_assets',
        ),
        migrations.AlterModelTable(
            name='domainassets',
            table='imu_domain_assets',
        ),
    ]
