# Generated by Django 2.2.6 on 2019-10-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20191017_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramassets',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SN号'),
        ),
    ]
